### ISSUE TITLE
PHASE 1 Todo List

### ISSUE THREAD

**Issue by ncrum** [keerthanakumar/cs373-idb#60]
### Here is what we still have to do for PHASE 1:
* [x] Unit Testing
* [x] APIary Documentation
* [x] Pydoc Documentation
* [x] Deploy to Rackspace
* [x] Technical Report
* [x] Redraw UML model
* [x] Add About Me's
* [x] Git commit log

Add others as comments to this issue.

**Comment by ncrum** [comment]
@fzohra once you finish up the unit tests (which sounds almost done) go ahead and check that off. Even if we don't have a testdb working. We can probably add that phase 2.

**Comment by ncrum** [comment]
@keerthanakumar once you finish up the pydoc or epydoc, check that off

**Comment by fzohra** [comment]
got it

**Comment by ncrum** [comment]
@keerthanakumar @fzohra @safaaleigh @YunJang anything else you have left to add to the technical report?

**Comment by fzohra** [comment]
also, the UML model on the about page should be updated. The pencil views drawing should be removed imo

**Comment by ncrum** [comment]
the About page on the website?

**Comment by ncrum** [comment]
Or the readme?

**Comment by fzohra** [comment]
sorry, I meant the readme

**Comment by ncrum** [comment]
Here is checklist for the Tech Report being done for you personally.
* [ ] @fzohra 
* [ ] @keerthanakumar 
* [ ] @YunJang 
* [ ] @safaaleigh 
* [ ] @ncrum

**Comment by keerthanakumar** [comment]
@fzohra Your about me picture is not loading!

**Comment by keerthanakumar** [comment]
@ncrum I can make a pdf of tech report once people are done. I think we still need a pdf for this part of the assignment.

**Comment by fzohra** [comment]
@keerthanakumar it loads on austiknights.tk for me

**Comment by keerthanakumar** [comment]
@fzohra It must not be a public link. Check the link on incognito! Also, if you are GDC I can come there.

**Comment by fzohra** [comment]
how do I get a public link? I'm using dropbox - that should be public.
 I'll head over to the GDC at around 8.

**Comment by keerthanakumar** [comment]
@fzohra  Not sure why it is not working. Can you send me your Dropbox link. I will try

**Comment by fzohra** [comment]
@keerthanakumar  https://dl-web.dropbox.com/get/chihiro.jpg?_subject_uid=250442646&w=AACF-nV60RIbX6KuUS1ZaCSyJvlzg48LAaNw6yrYQK_kVQ

**Comment by keerthanakumar** [comment]
Definitely not viewable :(
@fzohra

**Comment by fzohra** [comment]
@keerthanakumar changing it to cloudapp

**Comment by keerthanakumar** [comment]
@ncrum Pydoc has been created under html folder. Please check if it work. Frames.html should have all documentation. models-modules.html should be what they want.

**Comment by ncrum** [comment]
@keerthanakumar think we should just give them frames.html since it has models plus more?

**Comment by ncrum** [comment]
@keerthanakumar if we move any of those html files out of the html folder they break so we just have to tell the grader which one

**Comment by fzohra** [comment]
@keerthanakumar Joey Caudill just asked about that too on piazza

**Comment by ncrum** [comment]
@keerthanakumar can you change the repo name to idb instead of imdb before 10?

**Comment by fzohra** [comment]
@ncrum  KK changed it already

**Comment by ncrum** [comment]
@fzohra did you change migrate.py?
It now gives an error

**Comment by ncrum** [comment]
when it tries to migrate service type

**Comment by ncrum** [comment]
(DataError) value too long for type character varying(80)

**Comment by fzohra** [comment]
yeah, its erroring because Service has a value thats too long to fit in the db. . .

**Comment by fzohra** [comment]
I'll modify migrate to truncate the value. give me a sec.

**Comment by ncrum** [comment]
okay cool!

**Comment by fzohra** [comment]
actually, I just expanded place name from 80 to 250 char instead.

**Comment by fzohra** [comment]
it should work now

**Comment by ncrum** [comment]
sweet thanks, also @keerthanakumar the api routes work as such: `/api/places/Food`
`api/types` all work
