### ISSUE TITLE
[Phase 2] To-Do List

### ISSUE THREAD

**Issue by YunJang** [keerthanakumar/cs373-idb#68]
# Phase 2 Objectives

It looks like I will be the group leader for this phase. Here's what we should be doing for this phase:

Main Objectives:
* [x] Add in full-text search.
* [x] Add in Photos to the places we have.
* [x] Make lists of models sortable based on criteria.
* [x] Update Unit Testing
* [x] Update About Me to have major responsibilities and number of commits, issues, unit tests.
* [x] Update the technical report to reflect the changes made for Phase 2.

Optional:
* [x] Split up loading the results on our places in order to reduce page load times.
* [x] Clean up google.py (we can data mine more but right now it looks like we have enough with just prominence search)

I think that's mostly it since we already have majority of the requirements for Phase 2! But I'll add more or split things up.
